kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "creating namespace:dev; sleep 5 ; done"]
  restartPolicy: Never
